# Converting Data Structures to Arrays

#### Converting a Tuple to an Array:

In [1]:
import numpy as np  # Importing the NumPy library

tpl = (1, 2, 3)  # Creating a tuple with three elements
print(tpl)  # Printing the tuple
print(type(tpl))  # Printing the type of 'tpl' (should be <class 'tuple'>)
print('-' * 10)  # Printing a separator line for better readability

arr = np.array(tpl)  # Converting the tuple into a NumPy array
print(arr)  # Printing the NumPy array
print(type(arr))  # Printing the type of 'arr' (should be <class 'numpy.ndarray'>)

(1, 2, 3)
<class 'tuple'>
----------
[1 2 3]
<class 'numpy.ndarray'>


#### Converting a List to an Array:


In [2]:
import numpy as np  # Importing the NumPy library

lst = [1, 2, 3]  # Creating a Python list
print(lst)  # Printing the list
print(type(lst))  # Printing the type of 'lst' (should be <class 'list'>)
print('-' * 10)  # Printing a separator line for better readability

arr = np.array(lst)  # Converting the list into a NumPy array
print(arr)  # Printing the NumPy array
print(type(arr))  # Printing the type of 'arr' (should be <class 'numpy.ndarray'>)

[1, 2, 3]
<class 'list'>
----------
[1 2 3]
<class 'numpy.ndarray'>


#### Converting a Dictionary to an Array:

In [5]:
import numpy as np  # Importing the NumPy library

dct = {'a': 1, 'b': 2, 'c': 3}  # Creating a dictionary
print(dct)  # Printing the dictionary
print(type(dct))  # Printing the type of 'dct' (should be <class 'dict'>)
print('-' * 10)  # Printing a separator line for better readability

key_arr = np.array(list(dct))  #* You should use list(dct.keys()) for clarity
print(key_arr)  # Printing the NumPy array of keys
print(type(key_arr))  # Printing the type of 'key_arr' (should be <class 'numpy.ndarray'>)

arr = np.array(list(dct.values()))  # Converting the dictionary values into a NumPy array
print(arr)  # Printing the NumPy array
print(type(arr))  # Printing the type of 'arr' (should be <class 'numpy.ndarray'>)

{'a': 1, 'b': 2, 'c': 3}
<class 'dict'>
----------
['a' 'b' 'c']
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


#### Converting a Set to an Array

In [ ]:
import numpy as np  # Importing the NumPy library

set_data = {1, 2, k}  # Creating a set
print(set_data)  # Printing the set
print(type(set_data))  # Printing the type of 'set_data' (should be <class 'set'>)

arr = np.array(list(set_data))  # Converting the set into a NumPy array
print(arr)  # Printing the NumPy array
print(type(arr))  # Printing the type of 'arr' (should be <class 'numpy.ndarray'>)

{1, 2, 'k'}
<class 'set'>
['1' '2' 'k']
<class 'numpy.ndarray'>


#### Converting a String to an Array:

##### With converting to list

In [8]:
import numpy as np  # Importing the NumPy library

str_data = "hello world"  # Creating a string
print(str_data)  # Printing the string
print(type(str_data))  # Printing the type of 'str_data' (should be <class 'str'>)

ar = np.array(list(str_data))  # Converting the string into a NumPy array of characters
print(ar)  # Printing the NumPy array

print(type(ar))  # Printing the type of 'ar' (should be <class 'numpy.ndarray'>)

hello world
<class 'str'>
['h' 'e' 'l' 'l' 'o' ' ' 'w' 'o' 'r' 'l' 'd']
<class 'numpy.ndarray'>


##### Without Converting to list

In [9]:
import numpy as np  # Importing the NumPy library

str_data = "hello world"  # Creating a string
print(str_data)  # Printing the string
print(type(str_data))  # Printing the type of 'str_data' (should be <

arr = np.array(str_data)  # Converting the string into a NumPy arrayclass 'str'>)

print(type(arr))  # Printing the type of 'arr' (should be <class 'numpy.ndarray'>)

hello world
<class 'str'>
<class 'numpy.ndarray'>


#### Converting the Data Type of NumPy Arrays:

##### Converting an Array of Integers to Other Data Types

In [ ]:
import numpy as np  # Importing the NumPy library

# Creating a NumPy array with integer values
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Printing the original array

# Converting the integer array to a float array
arr_ = arr.astype('float')  # Each element is converted to float (e.g., 1 → 1.0)
print(arr_)  # Printing the converted float array

# Converting the integer array to a string array
arr_ = arr.astype('str')  # Each element is converted to a string (e.g., 1 → '1')
print(arr_)  # Printing the converted string array

# Converting the integer array to a boolean array
arr_ = arr.astype('bool')
print(arr_)  # Printing the boolean array (Any non-zero value becomes True, zero would be False)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[ True  True  True  True  True]


##### Converting an Array of Floats to Other Data Types:

In [11]:
import numpy as np  # Importing the NumPy library

# Creating a NumPy array with float values
arr = np.array([1., 2., 3., 4., 5.])
print(arr)  # Printing the original float array

# Converting the float array to an integer array
arr_ = arr.astype('int')  # Each float value is converted to an integer (decimal part is removed)
print(arr_)  # Printing the converted integer array

# Converting the float array to a string array
arr_ = arr.astype('str')  # Each float is converted to its string representation (e.g., 1.0 → '1.0')
print(arr_)  # Printing the converted string array

# Converting the float array to a boolean array
arr_ = arr.astype('bool')  # Any non-zero value becomes True
print(arr_)  # Printing the boolean array (all non-zero values → True)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
['1.0' '2.0' '3.0' '4.0' '5.0']
[ True  True  True  True  True]


##### Converting an Array of Strings to Other Data Types:

In [12]:
import numpy as np  # Importing the NumPy library

# Creating a NumPy array with string representations of numbers
arr = np.array(['1', '2', '3', '4', '5'])
print(arr)  # Printing the original string array

# Converting the string array to an integer array
arr_ = arr.astype('int')  # Each string number is converted to an integer
print(arr_)  # Printing the converted integer array

# Converting the string array to a float array
arr_ = arr.astype('float')  # Each string number is converted to a float
print(arr_)  # Printing the converted float array

# Converting the string array to a boolean array
arr_ = arr.astype('bool')  
print(arr_)  # Printing the boolean array (Non-empty strings convert to True)

['1' '2' '3' '4' '5']
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ True  True  True  True  True]


##### Converting an Array of Booleans to Other Data Types:

In [13]:
import numpy as np  # Importing the NumPy library

# Creating a NumPy array with boolean values
arr = np.array([True, False, False, False, True])
print(arr)  # Printing the original boolean array

# Converting the boolean array to an integer array
arr_ = arr.astype('int')  # True becomes 1, False becomes 0
print(arr_)  # Printing the converted integer array

# Converting the boolean array to a float array
arr_ = arr.astype('float')  # True becomes 1.0, False becomes 0.0
print(arr_)  # Printing the converted float array

# Converting the boolean array to a string array
arr_ = arr.astype('str')  # True becomes 'True', False becomes 'False'
print(arr_)  # Printing the converted string array

[ True False False False  True]
[1 0 0 0 1]
[1. 0. 0. 0. 1.]
['True' 'False' 'False' 'False' 'True']
