# Exploring Indexing and Slicing in NumPy

#### Indexing and Slicing in Lists:

In [6]:
# Creating a Python list
my_list = [1, 2, 3, 4, 5]

# Accessing elements using positive and negative indexing
print(my_list[0])   # First element (index 0) -> Output: 1
print(my_list[-1])  # Last element (negative index -1) -> Output: 5
print(my_list[2])   # Third element (index 2) -> Output: 3

# Slicing the list
print(my_list[1:4])  # Elements from index 1 to 3 (excluding index 4) -> Output: [2, 3, 4]
print(my_list[:3])   # First 3 elements (index 0 to 2) -> Output: [1, 2, 3]
print(my_list[3:])   # Elements from index 3 to the end -> Output: [4, 5]
print(my_list[::2])  # Every second element (step=2) -> Output: [1, 3, 5]
print(my_list[::-1]) # Reversed list (step=-1) -> Output: [5, 4, 3, 2, 1]

# Modifying elements in the list
my_list[0] = 10  # Changing the first element to 10
print(my_list)  # Output: [10, 2, 3, 4, 5]

# Deleting an element
del my_list[1]  # Deleting the element at index 1 (which was 2)
print(my_list)  # Output: [10, 3, 4, 5]

# Inserting elements at a specific position
my_list[1:1] = [20, 30]  # Inserting [20, 30] at index 1 without replacing any elements
print(my_list)  # Output: [10, 20, 30, 3, 4, 5]

1
5
3
[2, 3, 4]
[1, 2, 3]
[4, 5]
[1, 3, 5]
[5, 4, 3, 2, 1]
[10, 2, 3, 4, 5]
[10, 3, 4, 5]
[10, 20, 30, 3, 4, 5]


#### Indexing and Slicing in Array

In [7]:
import numpy as np  # Importing the NumPy library

# Creating a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Accessing elements using positive and negative indexing
print(my_array[0])   # First element (index 0) -> Output: 1
print(my_array[-1])  # Last element (negative index -1) -> Output: 5
print(my_array[2])   # Third element (index 2) -> Output: 3

# Slicing the array
print(my_array[1:4])  # Elements from index 1 to 3 (excluding index 4) -> Output: [2, 3, 4]
print(my_array[:3])   # First 3 elements (index 0 to 2) -> Output: [1, 2, 3]
print(my_array[3:])   # Elements from index 3 to the end -> Output: [4, 5]
print(my_array[::2])  # Every second element (step=2) -> Output: [1, 3, 5]
print(my_array[::-1]) # Reversed array (step=-1) -> Output: [5, 4, 3, 2, 1]

# Modifying elements in the NumPy array
my_array[0] = 10  # Changing the first element to 10
print(my_array)  # Output: [10, 2, 3, 4, 5]

# Deleting an element (but doesn't modify the original array)
np.delete(my_array, 1)  # Deletes element at index 1 (which is 2)
print(my_array)  # Output is still [10, 2, 3, 4, 5] because np.delete() returns a new array

# Inserting elements (but doesn't modify the original array)
np.insert(my_array, 1, [20, 30])  # Inserts 20 and 30 at index 1
print(my_array)  # Output is still [10, 2, 3, 4, 5] because np.insert() returns a new array

1
5
3
[2 3 4]
[1 2 3]
[4 5]
[1 3 5]
[5 4 3 2 1]
[10  2  3  4  5]
[10  2  3  4  5]
[10  2  3  4  5]


# Creating Fix Size Array and rendom number

### Creating Fixed Size Arrays:

Creating zeros array

In [12]:
import numpy as np
zeros_array = np.zeros(10)
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3), dtype = int)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----
[[0 0 0]
 [0 0 0]]


Creating Once

In [13]:
import numpy as np
ones_array = np.ones(10)
print(ones_array)
print('-----')

ones_array = np.ones((2, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3), dtype = int)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
-----
[[1 1 1]
 [1 1 1]]


Eye: NumPy's ' eye() ' function generates an identity matrix of the specified size.

In [14]:
import numpy as np
eye_array = np.eye(3)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4, dtype = int)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


### Random Number Generation:

In [16]:
import numpy as np
print(np.random.rand())
print(np.random.rand(10))
print(np.random.rand(3, 3))

print(np.random.randint(100))
print(np.random.randint(100, size=10))
print(np.random.randint(100, size=(3, 3)))
print(np.random.randint(low=100, high=200, size=(3, 3)))

# Generate a random number from a normal distribution with mean 0 and standard deviation 1
print(np.random.randn(10))

# Generate a 2D array of 3x3 random numbers from a uniform distribution between 0 and 1
print(np.random.uniform(size=(3, 3)))

# Generate a 2D array of 3x3 random numbers from a binomial distribution with n=10 and p=0.5
print(np.random.binomial(10, 0.5, size=(3, 3)))

# Poisson ,Exponential, Gamma, Chi-squared, T-distribution, F-distribution Beta Log-normal Laplace

0.8087210734036641
[0.40790246 0.38235015 0.06351345 0.3255201  0.22329475 0.00471718
 0.46219208 0.05860075 0.313211   0.63742947]
[[0.66860954 0.20626036 0.30614614]
 [0.4568091  0.8766948  0.9580424 ]
 [0.73969124 0.03073217 0.68127671]]
74
[94 32 28 46 91  3 93 83 26 55]
[[73 68 95]
 [19 11 42]
 [ 1 99 73]]
[[177 117 152]
 [156 161 138]
 [191 109 116]]
[-2.26861196  1.44205366 -1.36644795  0.77586589 -1.40598882  0.89997427
 -0.53948551  0.48136367  0.66958497 -0.11194254]
[[0.14906216 0.53792718 0.70871033]
 [0.29490429 0.82646229 0.02956342]
 [0.91024955 0.72292184 0.24727344]]
[[5 7 4]
 [8 3 5]
 [7 2 4]]


# Managing randomness with Seed

Generating Random Number

In [17]:
import numpy as np
print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.45290160050669315
[0.12767667 0.82468461 0.42936971]
6
[[6 0 5 8 7]
 [1 3 4 4 7]
 [9 4 1 4 8]]


Random Number with seed

In [18]:
import numpy as np
np.random.seed(2)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.43599490214200376
[0.02592623 0.54966248 0.43532239]
8
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]


Seed in Loops:



In [19]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(5)

# Run the loop 10 times
for i in range(10):
    # Generate an array of 1000 random integers (either 0 or 1)
    arr = np.random.randint(2, size=1000)
    
    # Count and print the number of ones and zeros in the array
    print(len(arr[arr == 1]), len(arr[arr == 0]))

505 495
509 491
481 519
508 492
510 490
490 510
503 497
475 525
496 504
499 501
