# Manipulating Multidimensional Arrays

### Creating Multi-dimensional Arrays:

##### Creating 2D array using list

In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


##### Creating 3D array using list

In [2]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


##### Creating a 2D Array from a List of Tuples:

In [7]:
import numpy as np  # Importing the NumPy library

arr = np.array([(1,2,3),(4,5,6)])
print(len(arr))
print(arr)  # Displaying the 2D array

2
[[1 2 3]
 [4 5 6]]


##### Creating a 2D Array from a List of Arrays

In [6]:
import numpy as np  # Importing the NumPy library

arr = np.array([np.array([1,2,3]), np.array([4,5,6])])
print(len(arr))
print(arr)  # Displaying the 2D array

2
[[1 2 3]
 [4 5 6]]


##### Creating a 2D Array form a List of String

In [8]:
import numpy as np  # Importing the NumPy library

arr = np.array(["Rohit", "Singh"])  # Creating a boolean array
print(len(arr))
print(arr)  # Displaying the array of strings

2
['Rohit' 'Singh']


##### Creating a 2D Array from a List of Dict

In [9]:
import numpy as np  # Importing the NumPy library

arr = np.array([{"name": "Rohit", "age": 25}, {"name": "Raju", "age": 30}])

print(len(arr))
print(arr)  # Displaying the array of dictionaries

2
[{'name': 'Rohit', 'age': 25} {'name': 'Raju', 'age': 30}]


#### Finding Details of array

In [16]:
import numpy as np
arr = np.array([[1,1],[4,1],[2,3]])

# todo : Printing the shape of the array
print("Shape of the array: ", arr.shape)

# todo : Printing the number of dimensions of the array
print("Number of dimensions: ", arr.ndim)

# todo : Printing the data type of the array elements
print("Data type of the array elements :", arr.dtype)

# todo : Printing the total number of elements in the array
print("Total number of elements :", arr.size)

# todo : Printing the size of each element of the array in bytes
print("Size of each element in bytes :", arr.itemsize)

Shape of the array:  (3, 2)
Number of dimensions:  2
Data type of the array elements : int64
Total number of elements : 6
Size of each element in bytes : 8
