## Array vs List


#### Arrays vs Lists Comparison:

In [6]:
import numpy as np  # Importing the NumPy library

lst = [1, 3, 2]  # Creating a Python list
print(lst)  # Printing the list
print(type(lst))  # Printing the type of 'lst' (should be <class 'list'>)
print('---')

arr = np.array([1, 2, 3])  # Creating a NumPy array from a list
print(arr)  # Printing the NumPy array
print(type(arr))  # Printing the type of 'arr' (should be <class 'numpy.ndarray'>)
print('---')

# Comparing NumPy array with the list (element-wise comparison)
# Since NumPy supports element-wise comparison, it returns an array of boolean values.
print(arr == lst)

# Convert NumPy array to a list and compare with 'lst' (this ensures both are lists)
print(arr.tolist() == lst)  # This will return True if both lists have the same elements in the same order

# Sorting both structures before comparison
# sorted(arr) converts NumPy array to a sorted list before comparing it with sorted(lst)
print(sorted(arr) == sorted(lst))  # This checks if both lists have the same elements regardless of order

[1, 3, 2]
<class 'list'>
---
[1 2 3]
<class 'numpy.ndarray'>
---
[ True False False]
False
True


#### Adding Element

In [11]:
import numpy as np  # Importing the NumPy library

lst = [1, 3, 2]  # Creating a Python list
arr = np.array([1, 2, 3])  # Creating a NumPy array from a list

print(lst)  # Printing the original list
lst.append(4)  # Appending an element (4) to the list (modifies the original list)
print(lst)  # Printing the updated list after appending
print('---')

print(arr)  # Printing the original NumPy array

# Appending an element (4) to the NumPy array
# Unlike lists, NumPy arrays are immutable, so np.append() creates a new array with the added element
arr = np.append(arr, 4)  # This does NOT modify the original array; instead, it returns a new one
print(arr)  # Printing the new array after appending

[1, 3, 2]
[1, 3, 2, 4]
---
[1 2 3]
[1 2 3 4]


#### Removing Element

In [12]:
import numpy as np  # Importing the NumPy library

lst = [1, 3, 2]  # Creating a Python list
arr = np.array([1, 2, 3])  # Creating a NumPy array from a list

print(lst)  # Printing the original list
del lst[-2]  # Deleting the second-to-last element from the list (index -2 refers to the second-to-last item)
print(lst)  # Printing the updated list after deletion
print('---')

print(arr)  # Printing the original NumPy array

# Deleting the second-to-last element from the NumPy array
# Unlike lists, NumPy arrays are immutable, so np.delete() creates a new array with the element removed
arr = np.delete(arr, -2)  # This does NOT modify the original array; instead, it returns a new one
print(arr)  # Printing the new array after deletion

[1, 3, 2]
[1, 2]
---
[1 2 3]
[1 3]


#### Updating Element

In [13]:
import numpy as np  # Importing the NumPy library

lst = [1, 3, 2]  # Creating a Python list
print(lst)  # Printing the original list

# Modifying elements in the list using negative indexing
lst[-2] = 2  # Changing the second-to-last element (-2 index) to 2
lst[-1] = 3  # Changing the last element (-1 index) to 3
print(lst)  # Printing the updated list after modifications
print('---')

arr = np.array([1, 3, 2])  # Creating a NumPy array
print(arr)  # Printing the original NumPy array

# Modifying elements in the NumPy array using negative indexing
arr[-2] = 2  # Changing the second-to-last element (-2 index) to 2
arr[-1] = 3  # Changing the last element (-1 index) to 3
print(arr)  # Printing the updated NumPy array after modifications

[1, 3, 2]
[1, 2, 3]
---
[1 3 2]
[1 2 3]


#### Performance Comparison

In [14]:
import numpy as np  # Importing the NumPy library
import time  # Importing the time module to measure execution time

# Creating a large list and a NumPy array with 10 million elements (0 to 9,999,999)
my_list = list(range(10000000))  # Python list with values from 0 to 9,999,999
my_array = np.arange(10000000)  # NumPy array with values from 0 to 9,999,999

# Measuring search time in the list
start_time = time.time()  # Start time
for _ in range(100):  # Run the search 100 times for more accurate measurement
    if 5000000 in my_list:  # Check if 5,000,000 exists in the list
        pass
end_time = time.time()  # End time
print('List : ', end_time - start_time)  # Print total time taken

# Measuring search time in the NumPy array
start_time = time.time()  # Start time
for _ in range(100):  # Run the search 100 times for more accurate measurement
    if 5000000 in my_array:  # Check if 5,000,000 exists in the NumPy array
        pass
end_time = time.time()  # End time
print('Array : ', end_time - start_time)  # Print total time taken

List :  4.368057012557983
Array :  0.8808727264404297
