# Working with copy function

#### Copy Function with Lists:

In [5]:
import numpy as np  # Importing the NumPy library (not used here but okay)


# Shallow copy example: lst1 references same list as lst (both share the same object)
lst = [1, 2, 3, 4, 5]
print(lst)
lst1 = lst
print(lst1)
print('-' * 10)

lst[0] = 5
print(lst)   # Change in lst affects lst1
print(lst1)  # lst1 shows change too
print('-' * 10)

lst1[0] = 4
print(lst)   # Changes reflect both ways
print(lst1)


print()
print('*' * 20)
print()


# Shallow copy using list.copy(): lst1 is a new list object with copied references (for immutable elements behaves like a deep copy)
lst = [1, 2, 3, 4, 5]
print(lst)
lst1 = lst.copy()
print(lst1)
print('-' * 10)

lst[0] = 5
print(lst)   # Change in lst DOES NOT affect lst1
print(lst1)  # lst1 remains unchanged here
print('-' * 10)

lst[0] = 1  # reset lst

lst1[0] = 5  # change lst1
print(lst)   # lst unchanged
print(lst1)  # lst1 changed


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[5, 2, 3, 4, 5]
[5, 2, 3, 4, 5]
----------
[4, 2, 3, 4, 5]
[4, 2, 3, 4, 5]

********************

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[5, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
----------
[1, 2, 3, 4, 5]
[5, 2, 3, 4, 5]


#### Copy Function with Arrays:

In [ ]:
 # todo Work same as list
import numpy as np
arr = np.array([1,2,3,4,5])

arr_ = arr
print(arr)
print(arr_)
print('-'*10)

arr[0] = 5
print(arr)
print(arr_)
arr[0] = 1
print('-'*10)

arr_[0] = 5
print(arr)
print(arr_)
arr_[0] = 1  # reset arr_

print()
print('*'*20)
print()

arr1 = arr.copy()
print(arr)
print(arr1)
print('-'*10)

arr[0] = 5
print(arr)
print(arr1)
arr[0] = 1
print('-'*10)

arr1[0] = 5
print(arr)
print(arr1)

[1 2 3 4 5]
[1 2 3 4 5]
----------
[5 2 3 4 5]
[5 2 3 4 5]
----------
[5 2 3 4 5]
[5 2 3 4 5]

********************

[1 2 3 4 5]
[1 2 3 4 5]
----------
[5 2 3 4 5]
[1 2 3 4 5]
----------
[1 2 3 4 5]
[5 2 3 4 5]
