# Saving Data in Files

### Saving Data in Text Files (.txt):

In [39]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.savetxt('data.txt', data, delimiter=',', fmt='%d')

#### Saving Data in Numpy Binary Files (.npy):

In [2]:
import numpy as np
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.save('data.npy', data)

#### Saving Data into csv file

In [24]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.savetxt('data.csv', data, delimiter=',', fmt='%d')

#### Saving Data into json file

In [12]:
# import numpy as np
# arr = np.array([[1,2,3],[4,5,6]])
# np.savetxt('data.json',arr, delimiter = ',', header = '{"data"  : [', footer = ']}', comments = '')  # * comments = '' to avoid # in header and footer

# todo : this is not still in proper json format You should import json module and convert array to list and then save it as json

import numpy as np
import json
arr = np.array([[1,2,3],[4,5,6]])
data_dict = {"data": arr.tolist()}  # Convert numpy array to list for JSON serialization
with open('data.json', 'w') as json_file:
    json.dump(data_dict, json_file, indent=4)


#### Saving data in yaml file

In [13]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.yaml',arr, delimiter = ',', header = '- data : ')

# Reading data from files

#### Reading data from text file

In [14]:
import numpy as np
loaded_data = np.loadtxt('data.txt', delimiter=',')
print(loaded_data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#### Reading data from numpy Binary files(.npy)

In [17]:
import numpy as np
loaded_data = np.load('data.npy')
print(loaded_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Reading data from csv file

In [25]:
import numpy as np
loaded_data = np.loadtxt('data.csv', delimiter=',')
print(loaded_data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


#### Reading data from json file

In [29]:
# import numpy as np
# data = np.loadtxt('data.json', delimiter = ',')
# print(data)

# todo : this also return and error because this code expects a text file with numerical data, but JSON format is not plain text with numbers.
# todo : To read JSON data, you should use the json module to parse the file.
import json
with open('data.json', 'r') as json_file:
    data_dict = json.load(json_file)
    data_array = np.array(data_dict['data'])
    print(data_array)

[[1 2 3]
 [4 5 6]]


#### Reading data from json file

In [30]:
import numpy as np
data = np.loadtxt('data.yaml', delimiter = ',')
print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


# Writing data in files

#### Replacing Existing Content:

In [32]:
import numpy as np
data = np.array([1,2,3])
np.savetxt('data-1.txt', data, delimiter = ',')

data = np.array([4,5,6])
np.savetxt('data-1.txt', data, delimiter = ',')

#### Appending Data to Existing Files:



In [43]:
import numpy as np
new_data = np.array([7,8,9])
data = np.loadtxt('data.txt', delimiter = ',')
data = np.vstack([data, new_data])
np.savetxt('data.txt', data, delimiter = ',')