# Dealing With Null Value

In [6]:
import numpy as np
arr = np.array([1, 2, 3, None, 4, 5, None])
print(arr == None)
arr[arr != None]

[False False False  True False False  True]


array([1, 2, 3, 4, 5], dtype=object)

In [12]:
import numpy as np
arr = np.array([1, 2, 3, np.nan, 4, 5, np.nan])
# arr[arr==None] = np.nan

print(arr[~np.isnan(arr)])

[1. 2. 3. 4. 5.]


#### Filling null with fix value

In [13]:
print(arr)
arr[np.isnan(arr)] = 0
print(arr)

[ 1.  2.  3. nan  4.  5. nan]
[1. 2. 3. 0. 4. 5. 0.]


#### Filling the null with avg

In [16]:
arr = np.array([1, 2, 3, np.nan, 4, 5, np.nan])
print("Array before filling:", arr)
arr[np.isnan(arr)] = np.mean(arr[~np.isnan(arr)])
print("Array after filling:", arr)

Array before filling: [ 1.  2.  3. nan  4.  5. nan]
Array after filling: [1. 2. 3. 3. 4. 5. 3.]


# Filtering and aggregation data with numpy

#### Filtering

In [43]:
import numpy as np

arr = np.random.randint(1, 11, size=(5,5))
arr

array([[ 4,  4,  9,  9, 10],
       [ 1,  1,  9,  9, 10],
       [ 2, 10,  3,  3,  8],
       [ 8,  6, 10,  7,  2],
       [ 8,  6,  9,  1,  8]], dtype=int32)

! Filter Element Greater then 5


In [44]:
arr[arr > 5]

array([ 9,  9, 10,  9,  9, 10, 10,  8,  8,  6, 10,  7,  8,  6,  9,  8],
      dtype=int32)

! Filter Element that are even


In [45]:
arr[arr % 2 == 0]

array([ 4,  4, 10, 10,  2, 10,  8,  8,  6, 10,  2,  8,  6,  8],
      dtype=int32)

! Filter element that are both even and greater than 5


In [46]:
arr[(arr % 2 == 0) & (arr > 5)]

array([10, 10, 10,  8,  8,  6, 10,  8,  6,  8], dtype=int32)

! Filtering value based on row

In [47]:
filteredarr = arr[2, :] > 5
print(arr[filteredarr])
filteredarr

[[ 1  1  9  9 10]
 [ 8  6  9  1  8]]


array([False,  True, False, False,  True])

#### Aggregation Function

! Sum

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.sum(arr))       # Total sum of all elements
print(np.sum(arr, axis=0))  # Sum of each column
print(np.sum(arr, axis=1))  # Sum of each row

45
[12 15 18]
[ 6 15 24]


! Mean

In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.mean(arr))
print(np.mean(arr, axis=0))  # Mean of each column
print(np.mean(arr, axis=1))  # Mean of each row

5.0
[4. 5. 6.]
[2. 5. 8.]


! Stendered Deviation

In [51]:
print(np.std(arr))        # Standard deviation of all elements
print(np.std(arr, axis=0))   # Standard deviation of each column
print(np.std(arr, axis=1))   # Standard deviation of each row

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


# Descriptive Statistics with NumPy

Descriptive Statistics Computation:

In [52]:
import numpy as np

# Generating a random array of 100 integers between 1 and 100
arr = np.random.randint(low=1, high=101, size=100)

# Computing mean and median
mean = np.mean(arr)
median = np.median(arr)

# Computing variance and standard deviation
variance = np.var(arr)
std_dev = np.std(arr)

# Computing quartiles (Q1, Q2, Q3) and interquartile range (IQR)
q1 = np.percentile(arr, 25)
q2 = np.percentile(arr, 50)  # Median is also the 50th percentile
q3 = np.percentile(arr, 75)
iqr = q3 - q1

# Computing skewness and kurtosis
skewness = np.mean((arr - mean) ** 3) / (std_dev ** 3)
kurtosis = np.mean((arr - mean) ** 4) / (std_dev ** 4)

# Printing the computed statistics
print('Mean      : ', mean)
print('Median    : ', median)
# print('Mode      : ', mode)  # Mode calculation is commented out as it's not directly available in NumPy
print('-'*20)

print('Variance  : ', variance)
print('Standard  : ', std_dev)
print('-'*20)

print('Q1        : ', q1)
print('Q2        : ', q2)
print('Q3        : ', q3)
print('-'*20)

print('IQR       : ', iqr)
print('Skewness  : ', skewness)
print('Kurtosis  : ', kurtosis)

Mean      :  51.85
Median    :  48.0
--------------------
Variance  :  857.9275000000001
Standard  :  29.290399451014665
--------------------
Q1        :  25.0
Q2        :  48.0
Q3        :  77.25
--------------------
IQR       :  52.25
Skewness  :  0.08817689902777909
Kurtosis  :  1.8043571817204793


# Sorting and Searching

#### Searching

! Linear search

In [58]:
import numpy as np
arr = np.array([1,3,4,6,5,7,12,3,13])
index = np.where(arr == 3)[0]
print(index)

[1 7]


! Binary Search

In [59]:
import numpy as np
arr = np.array([1,3,4,6,5,7,12,13])
index = np.searchsorted(arr, 3)
print(index)

1


! Searching Closest Value:


In [60]:
import numpy as np
arr = np.array([1,3,4,6,5,7,12,13])
index = np.argmin(abs(arr - 11))
print(index)

6


##### Sorting

! Quick Sort

In [61]:
import numpy as np
arr = np.array([5,7,9,0,3,1,6,2,4,8])
sorted_arr = np.sort(arr, kind = 'quicksort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]


! Heap Sort

In [62]:
import numpy as np
arr = np.array([5,7,9,0,3,1,6,2,4,8])
sorted_arr = np.sort(arr, kind = 'heapsort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]


! Merge Sort

In [63]:
import numpy as np
arr = np.array([5,7,9,0,3,1,6,2,4,8])
sorted_arr = np.sort(arr, kind = 'mergesort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]


# Data Cleaning With Numpy

### Masking With boolian array

In [65]:
arr = np.array([1,2,np.nan,4,5,np.nan])
print(np.isnan(arr))
print(~np.isnan(arr))
print(arr[np.isnan(arr)])
print(arr[~np.isnan(arr)])

[False False  True False False  True]
[ True  True False  True  True False]
[nan nan]
[1. 2. 4. 5.]


### Replacing outliers with a specific value

In [75]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr = arr[arr <= 8]
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

### Removing the duplicate

In [76]:
arr = np.array([1,2,3,4,5,6,5,3,2])
print(arr)
print(np.unique(arr))

[1 2 3 4 5 6 5 3 2]
[1 2 3 4 5 6]


##### Categorical data to one hot encoding

In [80]:
import numpy as np
categorical_arr = np.array(['A','B','C','D','E'])

numrical_arr = np.array([0,1,2,3,4])

print(categorical_arr)

one_hot_arr = np.eye(5)[numrical_arr]
print(one_hot_arr)

['A' 'B' 'C' 'D' 'E']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Normalization

In [81]:
import numpy as np
arr = np.array([10000,200000,300000,4000000,5000000])

normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[0.         0.03807615 0.05811623 0.7995992  1.        ]
