# A Deep Dive into range, arange, linspace & logspace

### Understanding range:

In [1]:
r = range(10)
print(r)

r = range(0,10, 2)
print(r)

r = range(10,0, -2)
print(r)

print(6 in range(10))
print(list(range(10)))

range(0, 10)
range(0, 10, 2)
range(10, 0, -2)
True
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Exploring arange:

In [3]:
import numpy as np
arr = np.arange(0,10,2)
print(arr)

arr1 = np.arange(10,0,-1)
print(arr1)

arr2 = np.arange(0,10,.5)
print(arr2)

[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


#### Exploring linspace:

In [4]:
import numpy as np
l = np.linspace(0,10,5)
print(l)

l = np.linspace(1,10,10)
print(l)

l = np.linspace(1,10,10, endpoint = False)
print(l)

l,s= np.linspace(1,5,10, retstep = True)
print(l)
print(s)

[ 0.   2.5  5.   7.5 10. ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
0.4444444444444444


#### Understanding logspace:

In [5]:
import numpy as np
arr = np.logspace(0,10,5)
print(arr)

arr = np.logspace(0,10,5, endpoint = False)
print(arr)

arr = np.logspace(0,10,5, base = 2)
print(arr)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]
[1.e+00 1.e+02 1.e+04 1.e+06 1.e+08]
[1.00000000e+00 5.65685425e+00 3.20000000e+01 1.81019336e+02
 1.02400000e+03]


# Array Manipulation Essentials : Reshaping, Flattening, Splitting & Merging

#### Flattening

In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

flat_arr = arr.flatten()
print(flat_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


#### Reshaping

In [7]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr.shape)
print('-'*10)

reshaped_arr = np.reshape(arr, (3,2))
print(reshaped_arr)

print(reshaped_arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
----------
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


#### Splitting:

In [17]:
import numpy as np
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)
print('-'*10)

# todo : vsplit
for _ in np.vsplit(arr, 4):
  print(_)
  
# todo : hsplit
print(np.hsplit(arr, 2))

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[[1 2 3 2]]
[[4 5 6 2]]
[[7 8 9 2]]
[[7 8 9 2]]
[array([[1, 2],
       [4, 5],
       [7, 8],
       [7, 8]]), array([[3, 2],
       [6, 2],
       [9, 2],
       [9, 2]])]


#### Split

In [25]:
import numpy as np
arr = np.array([[1,2,3,2],[4,5,6,2],[7,8,9,2],[7,8,9,2]])
print(arr)

print('-'*10)

split_arr = np.split(arr, 2, axis = 0)
print(split_arr)

[[1 2 3 2]
 [4 5 6 2]
 [7 8 9 2]
 [7 8 9 2]]
----------
[array([[1, 2, 3, 2],
       [4, 5, 6, 2]]), array([[7, 8, 9, 2],
       [7, 8, 9, 2]])]


#### marging

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,5,2,9])
arr3 = np.array([9,2,3,5])
arr4 = np.array([8,2,9,4])

# ! Concatenate
concat_arr = np.concatenate((arr1,arr2,arr3, arr4))

print(concat_arr)

# ! H-Stack
stacked_arr =  np.stack((arr1,arr2,arr3, arr4), axis = 1)
print(stacked_arr)

# ! V-Stack
vstacked_arr =  np.vstack((arr1,arr2,arr3, arr4))  # * Or you can write axis = 0
print(vstacked_arr)

[1 2 3 4 1 5 2 9 9 2 3 5 8 2 9 4]
[[1 1 9 8]
 [2 5 2 2]
 [3 2 3 9]
 [4 9 5 4]]
[[1 2 3 4]
 [1 5 2 9]
 [9 2 3 5]
 [8 2 9 4]]


# Advance Multidimensional Indexing

In [31]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[1,3,5]], [[7,8,9],[10,11,12],[4,5,3]], [[7,8,9],[10,11,12],[4,5,3]]])
print(arr)
print('-'*10)

# Access a specific Element
print(arr[0][1][2])
print(arr[0,1,2])
print('-'*10)

# Access a specific row
print(arr[0])
print(arr[0,:])
print(arr[0,:,:])
print(arr[:,0,:])
print(arr[:,:,0])
print('-'*10)

# Access with specific case
print(arr[[1,2], : , :])
print(arr[[1,2], : , 1])
print('-'*10)

# Access with specific conditions
print(arr[arr>5])
arr[arr >= 18] = True
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 1  3  5]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]]
----------
6
6
----------
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [7 8 9]
 [7 8 9]]
[[ 1  4  1]
 [ 7 10  4]
 [ 7 10  4]]
----------
[[[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]]
[[ 8 11  5]
 [ 8 11  5]]
----------
[ 6  7  8  9 10 11 12  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]
  [ 1  3  5]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]]


# Broadcasting for Efficient Calculations


#### Arithmetic Operations:



In [32]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

# Addition
print(a + 2)
print(a + b)
print('-'*10)


# Subtract
print(a - 2)
print(a - b)
print('-'*10)

# Multiplication
print(a * 2)
print(a * b)
print('-'*10)

# Division
print(a / 2)
print(a / b)
print('-'*10)

# Exponential
print(a ** 2)
print(a ** b)
print('-'*10)

# Modulo
print(a % 2)
print(a % b)
print('-'*10)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[3 4 5]
[[2 4 6]
 [5 7 9]]
----------
[-1  0  1]
[[ 0  0  0]
 [-3 -3 -3]]
----------
[2 4 6]
[[ 1  4  9]
 [ 4 10 18]]
----------
[0.5 1.  1.5]
[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]
----------
[1 4 9]
[[  1   4  27]
 [  1  32 729]]
----------
[1 0 1]
[[0 0 0]
 [1 2 3]]
----------


#### Comparision Operation

In [33]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

# >
print(a > b)
print('-'*10)

# <
print(a < b)
print('-'*10)

# >=
print(a >= b)
print('-'*10)

# <=
print(a <= b)
print('-'*10)

# ==
print(a == b)
print('-'*10)

# !=
print(a != b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[False False False]
 [False False False]]
----------
[[False False False]
 [ True  True  True]]
----------
[[ True  True  True]
 [False False False]]
----------
[[ True  True  True]
 [ True  True  True]]
----------
[[ True  True  True]
 [False False False]]
----------
[[False False False]
 [ True  True  True]]


#### Logical Operation

In [34]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

# >
print(a > b)
print('-'*10)

# <
print(a < b)
print('-'*10)

# >=
print(a >= b)
print('-'*10)

# <=
print(a <= b)
print('-'*10)

# ==
print(a == b)
print('-'*10)

# !=
print(a != b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[False False False]
 [False False False]]
----------
[[False False False]
 [ True  True  True]]
----------
[[ True  True  True]
 [False False False]]
----------
[[ True  True  True]
 [ True  True  True]]
----------
[[ True  True  True]
 [False False False]]
----------
[[False False False]
 [ True  True  True]]


#### Bitwise Operation

In [35]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

print(np.bitwise_and(a,b))

print(np.bitwise_or(a,b))

print(np.bitwise_xor(a,b))

print(np.bitwise_not(a,b))

print(np.right_shift(a,b))

print(np.left_shift(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[1 2 3]
 [0 0 2]]
[[1 2 3]
 [5 7 7]]
[[0 0 0]
 [5 7 5]]
[[-2 -3 -4]
 [-2 -3 -4]]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


# Locating Elements with where

#### Locating Elements in 1D Array:



In [42]:
import numpy as np  # Importing the NumPy library

np.random.seed(10)  # Setting the random seed for reproducibility

# Generating a 1D NumPy array of 10 random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=10)

print(arr)  # Printing the generated array
print('-' * 10)  # Printing a separator for better readability

# Finding the indices where the elements in the array are greater than or equal to 5
indices = np.where(arr >= 5)

# Printing the list of indices that satisfy the condition
print(list(indices[0]))  
print('-' * 10)  # Printing another separator

# Printing the actual values in the array that meet the condition
print(arr[indices])

[10  5  1  2 10  1  2  9 10  1]
----------
[np.int64(0), np.int64(1), np.int64(4), np.int64(7), np.int64(8)]
----------
[10  5 10  9 10]


#### Locating Elements in 2D Array:

In [43]:
import numpy as np  # Importing the NumPy library

np.random.seed(10)  # Setting the random seed for reproducibility

# Generating a 3x3 NumPy array with random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=(3, 3))

print(arr)  # Printing the generated 3x3 matrix
print('-' * 10)  # Printing a separator for better readability

# Finding the indices where the elements in the array are greater than or equal to 5
indices = np.where(arr >= 5)

# Printing the tuple of arrays containing row and column indices of elements satisfying the condition
print(indices)
print('-' * 10)  # Printing another separator

# Printing the actual values in the array that meet the condition
print(arr[indices])

[[10  5  1]
 [ 2 10  1]
 [ 2  9 10]]
----------
(array([0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2]))
----------
[10  5 10  9 10]


#### Locating Elements in 3D Array:

In [44]:
import numpy as np  # Importing the NumPy library

np.random.seed(10)  # Setting the random seed for reproducibility

# Generating a 3x3x3 NumPy array with random integers between 1 and 10 (inclusive)
arr = np.random.randint(1, 11, size=(3, 3, 3))

# Printing the generated 3D array
print(arr)
print('-' * 10)  # Printing a separator for better readability

# Finding the indices where the elements in the array are greater than or equal to 5
indices = np.where(arr >= 5)

# Printing the tuple of arrays containing indices of elements satisfying the condition
# indices[0] -> first dimension (depth)
# indices[1] -> second dimension (rows)
# indices[2] -> third dimension (columns)
print(indices)
print('-' * 10)  # Printing another separator

# Printing the actual values in the array that meet the condition
print(arr[indices])

[[[10  5  1]
  [ 2 10  1]
  [ 2  9 10]]

 [[ 1  9  7]
  [ 5  4  1]
  [ 5  7  9]]

 [[ 2  9  5]
  [ 2  4  7]
  [ 6  4 10]]]
----------
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 2, 1, 2, 2, 0, 2]))
----------
[10  5 10  9 10  9  7  5  5  7  9  9  5  7  6 10]
